services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=real-time-chat'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
